/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan1;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahend
 * 
 */
public class ArsipSurat extends javax.swing.JFrame {
private Connection con;
private Statement stat;
private ResultSet res;

    /**
     * Creates new form ArsipSurat
     */
    public ArsipSurat() {
        initComponents();
        koneksi();
        KodeSurat();
        JenisSurat();
        tabel();
        kosongkan();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width)/2,
        (screenSize.height - frameSize.height)/3);
    }
    
    private void KodeSurat(){
        KodeSurat.addItem("1 (Surat Masuk)");
        KodeSurat.addItem("2 (Surat Keluar)");
        KodeSurat.removeItem("Item 1");
        KodeSurat.removeItem("Item 2");
        KodeSurat.removeItem("Item 3");
        KodeSurat.removeItem("Item 4");
        KodeSurat.setSelectedIndex(-1);
    }
    
    private void JenisSurat(){
        JenisSurat.addItem("Resmi");
        JenisSurat.addItem("Umum");
        JenisSurat.addItem("Pribadi");
        JenisSurat.removeItem("Item 1");
        JenisSurat.removeItem("Item 2");
        JenisSurat.removeItem("Item 3");
        JenisSurat.removeItem("Item 4");
        JenisSurat.setSelectedIndex(-1);
    }
    
    private void kosongkan()
    {
        NomorSuratTF.setText("");
        PengirimTF.setText("");
        PenerimaTF.setText("");
        TanggalMasukTF.setText("");
        TanggalSuratTF.setText("");
        PerihalSuratTF.setText("");
        NomorSuratTF.requestFocus();
        KodeSurat.setSelectedIndex(-1);
        JenisSurat.setSelectedIndex(-1);
    }
    private DefaultTableModel dtm;
    private void koneksi() { 
        try { Class.forName("com.mysql.jdbc.Driver"); 
    con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_arsip", "root", ""); 
    stat=con.createStatement(); 
    } catch (Exception e){ 
        JOptionPane.showMessageDialog(null, e); 
    }
    }
    
    private void tabel(){ 
        DefaultTableModel t= new DefaultTableModel(); 
        t.addColumn("Nomor Surat"); 
        t.addColumn("Pengirim"); 
        t.addColumn("Penerima"); 
        t.addColumn("Tanggal Masuk"); 
        t.addColumn("Tanggal Keluar"); 
        t.addColumn("Tanggal Surat"); 
        t.addColumn("Perihal Surat"); 
        t.addColumn("Kode Surat");
        t.addColumn("Jenis Surat"); 
        TableSurat.setModel(t); 
        try{ res=stat.executeQuery("select * from data_arsip"); 
        while (res.next()) { 
            t.addRow(new Object[]{ 
            res.getString("nomor_surat"), 
            res.getString("pengirim"), 
            res.getString("penerima"), 
            res.getString("tanggal_masuk"),
            res.getString("tanggal_keluar"),
            res.getString("tanggal_surat"),
            res.getString("perihal_surat"),
            res.getString("kode_surat"),
            res.getString("jenis_surat") 
        }); 
        } 
        }catch (Exception e) 
        { JOptionPane.showMessageDialog(rootPane, e); }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        KodeSurat = new javax.swing.JComboBox<>();
        NomorSuratTF = new javax.swing.JTextField();
        PengirimTF = new javax.swing.JTextField();
        PenerimaTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TanggalMasukTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JenisSurat = new javax.swing.JComboBox<>();
        TanggalSuratTF = new javax.swing.JTextField();
        TanggalKeluarTF = new javax.swing.JTextField();
        PerihalSuratTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSurat = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ARSIP SURAT");

        KodeSurat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Kode Surat");

        jLabel3.setText("Nomer Surat");

        jLabel4.setText("Pengirim");

        jLabel5.setText("Penerima");

        jLabel6.setText("Tanggal Masuk");

        jLabel7.setText("Tanggal Keluar");

        jLabel8.setText("Tanggal Surat");

        jLabel9.setText("Jenis Surat");

        jLabel10.setText("Perihal Surat");

        JenisSurat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("SURAT MASUK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("SURAT KELUAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("HOME");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        TableSurat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableSurat);

        jLabel11.setText("M.R.DWIMAHENDRA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(841, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jButton7))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PengirimTF)
                                    .addComponent(PenerimaTF)
                                    .addComponent(TanggalMasukTF)
                                    .addComponent(NomorSuratTF, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KodeSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TanggalKeluarTF, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(TanggalSuratTF)
                                            .addComponent(PerihalSuratTF)
                                            .addComponent(JenisSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PengirimTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PenerimaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KodeSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(TanggalKeluarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NomorSuratTF)
                                .addComponent(jLabel8)
                                .addComponent(TanggalSuratTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(JenisSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PerihalSuratTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TanggalMasukTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableSuratMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        int i = TableSurat.getSelectedRow();
            if(i==-1){
            return;
            }
            String code = (String)TableSurat.getValueAt(i,0);
            String code1 = (String)TableSurat.getValueAt(i,1);
            String code2 = (String)TableSurat.getValueAt(i,2);
            String code3 = (String)TableSurat.getValueAt(i,3);
            String code4 = (String)TableSurat.getValueAt(i,4);
            String code5 = (String)TableSurat.getValueAt(i,5);
            String code6 = (String)TableSurat.getValueAt(i,6);
            String code7 = (String)TableSurat.getValueAt(i,7);
            String code8 = (String)TableSurat.getValueAt(i,8);
            NomorSuratTF.setText(code);
            PengirimTF.setText(code1);
            PenerimaTF.setText(code2);
            TanggalMasukTF.setText(code3);
            TanggalKeluarTF.setText(code4);
            TanggalSuratTF.setText(code5);
            PerihalSuratTF.setText(code6);
            KodeSurat.setSelectedItem(code7);
            JenisSurat.setSelectedItem(code8);
    }                                       

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
new Home().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Record ini???","Confirmation",JOptionPane.YES_NO_OPTION);
        try
        {
            String sql="update data_arsip set nomor_surat=?,pengirim=?,penerima=?,tanggal_masuk=?,tanggal_keluar=?,tanggal_surat=?,perihal_surat=?,kode_surat=?,jenis_surat=? where nomor_surat='"+NomorSuratTF.getText()+"'";
            PreparedStatement st=con.prepareStatement(sql);
            if(ok==0)
            {
            try
            {
            st.setString(1,NomorSuratTF.getText());
            st.setString(2,PengirimTF.getText());
            st.setString(3,PenerimaTF.getText());
            st.setString(4,TanggalMasukTF.getText());
            st.setString(5,TanggalKeluarTF.getText());
            st.setString(6,TanggalSuratTF.getText());
            st.setString(7,PerihalSuratTF.getText());
            st.setString(8, (String) KodeSurat.getSelectedItem());
            st.setString(9, (String) JenisSurat.getSelectedItem());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Update Data Sukses");
            }catch (Exception e)
            {
            JOptionPane.showMessageDialog(null, "Update Data Gagal");
            }
            }
            }catch (Exception e){}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
            String sql="delete from data_arsip WHERE nomor_surat='"+NomorSuratTF.getText()+"'";
            PreparedStatement st=con.prepareStatement(sql);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Data Sukses");
            }catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Object [] rows={"Nomor Surat","Pengirim","Penerima","Tanggal Masuk","Tanggal Keluar","Tanggal Surat","Perihal Surat","Kode Surat","Jenis Surat"};
            dtm=new DefaultTableModel(null,rows);
            TableSurat.setModel(dtm);
            TableSurat.setBorder(null);
            jScrollPane1.setVisible(true);
            jScrollPane1.setViewportView(TableSurat);
            int no = 1;
            String nomor_surat="",pengirim="",penerima="",tanggal_masuk="",tanggal_keluar="",tanggal_surat="",perihal_surat="",kode_surat="",jenis_surat="";
            try{
            String sql="select * from data_arsip";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
                while(rs.next()){
                nomor_surat=rs.getString("nomor_surat");
                pengirim=rs.getString("pengirim");
                penerima=rs.getString("penerima");
                tanggal_masuk=rs.getString("tanggal_masuk");
                tanggal_keluar=rs.getString("tanggal_keluar");
                tanggal_surat=rs.getString("tanggal_surat");
                perihal_surat=rs.getString("perihal_surat");
                kode_surat=rs.getString("kode_surat");
                jenis_surat=rs.getString("jenis_surat");
                String [] tampil={""+nomor_surat,pengirim,penerima,tanggal_masuk,tanggal_keluar,tanggal_surat,perihal_surat,kode_surat,jenis_surat};
                dtm.addRow(tampil);
                }
            }catch(SQLException e){
                e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Query Salah "+e);
                }
            }catch(Exception e){
                e.printStackTrace();
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            res=stat.executeQuery ("select * from data_arsip where "+ "nomor_surat='" +NomorSuratTF.getText()+"'" );
            while (res.next()) {
                PengirimTF.setText(res.getString("pengirim"));
                PenerimaTF.setText(res.getString("penerima"));
                TanggalMasukTF.setText(res.getString("tanggal_masuk"));
                TanggalKeluarTF.setText(res.getString("tanggal_keluar"));
                TanggalSuratTF.setText(res.getString("tanggal_surat"));
                PerihalSuratTF.setText(res.getString("perihal_surat"));
                KodeSurat.setSelectedItem(res.getString("kode_surat"));
                JenisSurat.setSelectedItem(res.getString("jenis_surat"));
            }
        }catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e); }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
new ArsipSuratMasuk().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
new ArsipSuratKeluar().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArsipSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArsipSurat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JenisSurat;
    private javax.swing.JComboBox<String> KodeSurat;
    private javax.swing.JTextField NomorSuratTF;
    private javax.swing.JTextField PenerimaTF;
    private javax.swing.JTextField PengirimTF;
    private javax.swing.JTextField PerihalSuratTF;
    private javax.swing.JTable TableSurat;
    private javax.swing.JTextField TanggalKeluarTF;
    private javax.swing.JTextField TanggalMasukTF;
    private javax.swing.JTextField TanggalSuratTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
